<a href="https://colab.research.google.com/github/25ds3000042/ML-Algorithms-Using-NumPy/blob/main/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.arange(12).reshape(3, 4)

print(A)
print("shape:", A.shape)
print("dtype:", A.dtype)
print("strides:", A.strides)

B = A[:, ::3]

print("\nB:")
print(B)
print("shape:", B.shape)
print("strides:", B.strides)

print("\nShares memory:", np.shares_memory(A, B))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
shape: (3, 4)
dtype: int64
strides: (32, 8)

B:
[[ 0  3]
 [ 4  7]
 [ 8 11]]
shape: (3, 2)
strides: (32, 24)

Shares memory: True
